### ISSUE TITLE
SDK path error

### ISSUE THREAD

**Issue by CapperLabs** [OpenAcousticDevices/AudioMoth-Project#2]
Installed new Simplicity IDE (SV4.1.12.1) and updated per instructions on WIKI
https://github.com/OpenAcousticDevices/AudioMoth-Project/wiki/AudioMoth

Studio Packages installed are:
GNU ARM Toolchain (v4.9.2015.q3)
GNU ARM Toolchain (v7.2.2017.q4)
32 bit MCU SDK - 5.7.3.0
32 bit MCU SDK - 5.8.4.0

Trying to import AudioMoth-Project I get error:
"SDK of the build configuration cannot be resolved."
Specifically it doesn't like the line in .cproject:

value="${StudioSdkPathFromID:com.silabs.sdk.stack.super:1.1.0._1914564505}"/>

**Comment by pcprince** [comment]
Currently responding to issue here: https://www.openacousticdevices.info/support/device-support/sdk-path-error-compiling-audiomoth-project
Will copy over solution to this issue page when found.

**Comment by CapperLabs** [comment]
Solution - install 32 bit MCU SDK - 5.2.2.0
