### ISSUE TITLE
Feature Request: USB Audio Output

### ISSUE THREAD

**Issue by alexschultze** [OpenAcousticDevices/AudioMoth-Project#4]
I recommend a output feature (USB Audio device or serial). This would allow integrating this into upstream (4g, wifi, ...) observation networks easily without the need of adding those features on the AudioMoth.

**Comment by alexschultze** [comment]
Reference Example for ESM32:
https://www.silabs.com/community/mcu/32-bit/knowledge-base.entry.html/2016/04/04/usb_audio_examplesf-k9Zz

**Comment by AlexRogersCS** [comment]
See https://www.openacousticdevices.info/usb-microphone.

**Comment by AlexRogersCS** [comment]
Done. See the AudioMoth USB Microphone firmware.
