### ISSUE TITLE
Record every other day

### ISSUE THREAD

**Issue by JKSheard** [OpenAcousticDevices/AudioMoth-Project#5]
Hi,

Would it be possible to add a new feature so that you can program the AudioMoth to record every other day or every third day etc.?
We have used the AudioMoths for sound indexes and there seems to be very little information lost if we e.g. only record every other day, on the other hand it would significantly reduce the necessary storage space and analysis time. A huge benefit. Maybe you or someone else has already looked into this?

Alternatively, could you point me to the part of the code where I might be able to change this myself?

Best,
Julie

**Comment by AlexRogersCS** [comment]
We are looking at adding a scripting option for the standard firmware. The time of the next recording period is calculated in the scheduleRecording function and you can check the day of the week there, or the day of the year, and skip the day if it is not appropriate to record.
